/////////////////////////////////////////////////////////////////////////////
// FIX ME
// set new contract address
/////////////////////////////////////////////////////////////////////////////
export const  contractAddress = "KT1QNURPMuFJSmTLRttRutb4gfJ6NS4BfsM6"

/* export const mockupIdeas =  [
  { id: "1",
    winner: false,
    title: "GoUwLiBOCGB2DOACAItAniglvAxgewFdYxEAzPSRAN3CjniA",
    desc: "JIAg7g9grgNgJiGBLA1gUxAFwiADgJwlwgGcNMALAQ0xGDjSoGEJ9cA6EAYwgDsSkDfHkIA3QUl4BzEAFskyTFXwBPEKLSY0+KvxBU5EBiVpwkJHlF60+IAGqbtukiDhU1jLhRArG+TqBUsvpgyuTUtCrQIOhouD7QwgRIXJIyMBBgWDgEEOIMWBQYAEZoJupUMFAYAGashRiyfGgqnAASmWgawrK6aviaVAraLrn5jQpISqqu5pbWLpUwPn6IfFKcAMoQshhdaLyu0MUw4TSzFtDWILYaWjp6bq0gAIKL6o4PiEji0jeHBiaxlouAOAlslXW4Cm3hIEFSlRAZC4UHwUxUABo6CBqBpsnhJF48AdeEgyvpeAgMhAUCA6sIBoiGJUSAEag0BuBtBhAUYyqY5lcbDUatyEHwuDyVsosaB5FIKLRSvoTuQcCRcFV8FIMBCQLw0FkACp2G7CHiyXBQe7sIA=",
    author: "tz1ZXf37ZNfVupt5GVyrPJ76q8kbjFuD2z7R",
    creation: "2020-10-01",
    nbvotes: 10 },
  { id: "2",
    winner: true,
    title: "EoUwbglmIAQOIEMC2IBOBnGBhANgVwCMYBVAOxwHsBjAaxABMBCIA",
    desc: "CoewBA7gFiC2YEsAuZYEMCeYDGIB22ApgE54A0YAkmElAngNZVgDOADoWkwGYjE0wArizR4AJizAhuVMZwDCfNgDowhWGwA2IDIUKTRYnMKRwSB7MRAtJtQmACqeZISMBlJGiT6A9PNFoYmiQMGByHOJggmz4sgpKqrz8IIL8AOZosPRpYHiERDbICPqqAIIGcWiKxCpqGtq69tSEAG6EeGC8gpHttMIIaCzw9FLc3CTZYADimeZg8pqCAEaOeNrYDK404LBY2CZmxCyqAOr2g2DBuLCw3chY0mp4fSwDLEiSCPV8TXJVCdswMRCABaejvZCCbzTWZHeaLFZOdabIx8S4daJBbxGWDqJbmOhsSDIKCsL4ITRofj4vLcZDHMAnEkpFC0BCSXGwfFHQmAu7QjK4uGmSrVFQUagsPS5cCaehMEWbQhEwWTfbvQ6SNipbBQQaTbhWeCUP5i5SqYB6xhgDApZRAA=",
    author: "tz1Lc2qBKEWCBeDU8npG6zCeCqpmaegRi6Jg",
    creation: "2020-10-21",
    nbvotes: 40 },
  { id: "3",
    winner: false,
    title: "EwBgpABAJglgzgYwPYFcB2AXCSBmOIBuMUApkhAOYCGAtiRFQgiXHEgE4wsQ4cQDiAYQCqEeA2gsEnAA4YYSNEA=",
    desc: "EwBgpABAJglgzgYwPYFcB2AXCSBmOIBuMUApkhAOYCGAtiRFQgiXHEgE4wsQ4cQDiAYQCqEAJIBZAPIQ2EDAAt4sqkTQU4EAO6oANlAgAHdiQwYAnhBooECiCTRwUJ8aSqCOhgHSVTmxfRwVLokPlIB7BAmGFQwIeyaAGQQAEIp0OTs6BAAjOAANLkArJDJoJC4+FQ8JFryMHSahiSR5pEARihYMFhwJCQ0mrowANb0ARA9AwAUcACUEOaoVlSWaP1QAPRaVJgQCqoOAAZY7exIY4umYZERJEeaAMoAopsAMs/yB1hLKEcuWjiw3U8nIhlWPD4nSwE2MSBo5HgaBOkzQ9jwJAQGC8QA=",
    author: "tz1ZAQXACaEqryobpBoLbJUc2DjG5ZzrhARu",
    creation: "2020-10-25",
    nbvotes: 29 },
  { id: "4",
    winner: false,
    title: "OISwZgLgBAwghgJwCYGcCEag",
    desc: "OoCwngBAxghgdgFwgSQgGwPYwCYQLaQDmAlgGZKwBO2AzhMYhvpDFFBgK6IQ1MIgwkqGGgDuMMHQEA3AKYQYEAEYj4UeQiYca86TQB0EGQ0IRNEWXBodKGgUKMw5ZkPKq0Io4v3zzRruBQzSidZNEMIAE1OBVt8YhoaEwhOJAxAgAkAVQBxAFEUgAdCjEoELm8wCNQAK20kbVlcAEE8GAAvdPorBFkcFNIUbD6AYVLCw1JSlwSIOUpIWxheOGrPZYUlNA0mQiZKYkIQJHMCZVU4dU9vEFTHaWSfQvAk2DRoGGoI/IAVFAA5H4AeQgPwyyAAyhARnlAVkAEqRCAABQAMnlmhC8gBCbEQFB/SEQZoQeEY1GghH/CBAgBitNBIIAIiCAEJZCHIf55CFQ4DIMFRIEIiAQ4Fk/RAA",
    author: "tz1YwPJUNoU9qQTtFtsg6mjWUGSkXtf2uDHc",
    creation: "2020-12-03",
    nbvotes: 15 },
  { id: "5",
    winner: true,
    title: "KIQwTgNgngBAggYwQUwM6pgMwPZhsCASwBdkB6Ak5GABQgFcMBaGAIQhAQGsYAxMQgBMQsAEwAGUQEYgA===",
    desc: "MoSwdgxgpgBAQgMRgJgAwEYCcMDuBDAZxjwHM9wYATEAvABzoHtwAXcEmAM0YCcYBXIgFEANiBawAtlEkAjKDwIAaGAElceMCxgtGMANZhGOGAUaMwKo9sp4AnkXncesEJxhgoAD212oePlVKfwBhXjoAOlwQEREYeXiednZ4vAh9XAALPG0hAJE7GABBCGgCIkEoSh09eQBuYhg6BQznHUzGAlgcDph/Hk9q8Sj1TWrGFkyFIimXGDIAN1h+Onn+AM0JKqaW5RgIQkzU9OIwapYePCW4yRioIhxxI4nZ/YgAciIx+MK6fh4INkCCkcmpgngwjxIiolopBPtGJJmmxdIoogA1BSFai0BjMLQpDomcAECR4cbuFz4HjUMAcOyMf4wESMOx4OIQQS6aSKFQM/g6f5gGD8viyNIZCwCAgjPoAR3WEnaNGikyaPERnXaoKpAWqnBAim0bGk8X4fkUMF4pn4sgIECS8ktjzV5OobAs7KoNAgjK0REmoMoFne2nodAKNT6XhobDpMGkcmmESAA",
    author: "tz1XZ7s6uStC2hZVpPQhXgcdXPwxifByF3Ao",
    creation: "2020-12-04",
    nbvotes: 7 },
  { id: "6",
    winner: false,
    title: "IIGxHsHcEsDsHMAEABA4gQwLYFMBOiBhcAVwAdxYBnRAF3EQCNtFjLsATRCkObIA",
    desc: "JIcgbgpgBAdg9gFwJYGMIBMoIBYEMFbYQBOEIAzlAEYQQxS5QA2uxA5tAGZwoCulcevwxQ2uALYRKAMkIkylGnSjkIkYriZQAAmMnEoKOLwAOgytwPDMeqYXxQ8kKKXK8mCEUnps4cTOgQmuQAdFAAQrwEONAmxHBUTBDiUJZQ4rgwAJ5QSJQ4DjFIBkw8mioIcK5Q6IIgBE7QjCzs0KpJKMiCUHCcUNaiEnYA7tio2Om4ANZ2MYbGZjCUAETCSeTky2EAgkzkcAA0UKPKMaQUNUF7zEgz1Lw5AEyiEAQAjKmk0N2aWgO2AgMVAeDGy/VUNiGUAAJABmAAMPQM4iq0A4BEYnC+UAAqjBSigZphJOIaMRyGMTHJVAxSAw9nBYIgoHRkChvGxcn0zgobggEEksIz4INJEL7lkQkA==",
    author: "tz1UUHt41ukVHcamQ5YZgGWsm6mXasVBt6Ln",
    creation: "2020-12-05",
    nbvotes: 2 },
  { id: "7",
    winner: false,
    title: "IIExEsBdwewOwIYBsAEBxBBbApgJwM4oDCSArgEYoCqcSMAxgNbYgoBC2c2AZlPkA===",
    desc: "AQWgggLsA2CmCGBnKBGYsAeBjaBXRAlgG6zBEEAmsA9sAObwC2pATrNPBLBcFfNMGoAzYBAAWpCvACewAA6wWwAO6xYAa1DAAotjyES8tuVjLBI3HKzVGBAHZ1gifrEQB6OSxvUIBanfc+aER5RRU1TWolRn9xADpQAGUFLAJ+YGtLf0E7YGlqXCUAIwIWcSlpOKA===",
    author: "tz1cck7sNvM3TWkUA9VGWnyBW44uxMLz9vGg",
    creation: "2020-12-06",
    nbvotes: 7 },
  { id: "8",
    winner: false,
    title: "BIVw5gpgBGCWYEMB2AXWBjKAjZSICcg=",
    desc: "AoVwLgBAhhAWIHMCmAaCCCWCoDswYGMIAjXHJAJwgHsA3SiMWJCAFQDUIATJABygpgAtkjwQAzmCj4cCCADMKSFjwA2GehQCeC6lVw6ONTRACsABgBEAOggB1DE2jcM4gqqgYRVJtOg5DdgBycQkkVXlucI1KJC4IAHcMVVUIHGpIYhYlMBAKHChiVRZ5PQheWC1xQihUrighKGRLIA=",
    author: "tz1ZXf37ZNfVupt5GVyrPJ76q8kbjFuD2z7R",
    creation: "2020-12-07",
    nbvotes: 8 },
]
 */

/* export const mockupIdeas =  [
    { id: "0",
      winner: false,
      title: "Veterans Day Discount for veterans",
      desc: "I would like to propose that IdeaCorp. consider providing military veterans a modest discount on Veterans day each year. I am aware that you keep your pricing low to provide the best value for the money. However many retailers provide military discounts all year long. Some even double that discount on veterans day. As a veteran living on a modest pension along with social security, I have to pinch pennies and look for real deals. If there were a modest discount offered once a year, I might be able to splurge on a new TV or computer.",
      author: "tz1ZXf37ZNfVupt5GVyrPJ76q8kbjFuD2z7R",
      creation: "2020-10-01",
      nbvotes: 10 },
    { id: "1",
      winner: true,
      title: "Revive Gamers Club Unlocked!",
      desc: "To whom it may concern, I think I speak for thousands of IdeaCorp. employees and customers across the United States/Canada who depend upon IdeaCorp. for our gaming necessities. As a IdeaCorp. employee I even found enthusiasm in offering Gamers Club Unlocked to my customers. We as a community of enthusiasts implore IdeaCorp. to re-institute Gamers Club Unlocked or an updated membership with similar benefits. Without this membership to unite gamers to IdeaCorp., I see no link to keep gaming customers purchasing from IdeaCorp.. Thank you.",
      author: "tz1Lc2qBKEWCBeDU8npG6zCeCqpmaegRi6Jg",
      creation: "2020-10-21",
      nbvotes: 40 },
    { id: "2",
      winner: false,
      title: "20% discount off video game accessories for GCU is a description",
      desc: "20% discount off video game accessories for GCU IMO so this savings would pretty much ensure IdeaCorp. gets the sale. Other retailers & BB do run 10%, 15% & 20% off a few times per yr but it seems like the item(s) you may need/want haven`t broke yet. Or there`s SE/LE that you`re willing to pay for but the promo isn`t in effect.",
      author: "tz1ZAQXACaEqryobpBoLbJUc2DjG5ZzrhARu",
      creation: "2020-10-25",
      nbvotes: 29 },
    { id: "3",
      winner: false,
      title: "Gift Cards!!",
      desc: "Why cant I load my gift cards into my account so that I always have a balance to use vs. having to ensure that I have the cards with me when I travel.  You are missing out on HUGE opportunity.  I just used Amazon instead of IdeaCorp. for this very reason.  I was able to go right to my balance without having th physical card.  GET INTO THIS CENTURY PLEASE!!  IT IS A REAL TURN OFF TO DO BUSINESS WITH YOUR STORE.",
      author: "tz1YwPJUNoU9qQTtFtsg6mjWUGSkXtf2uDHc",
      creation: "2020-12-03",
      nbvotes: 15 },
    { id: "4",
      winner: true,
      title: "Early Access for Elite/Elite Plus - Black Friday 2021",
      desc: "Since BF 2019 was again disappointing for us Elite members, I want to know soon, not days before if next year IdeaCorp. will be bringing back what Early Access used to be; a perk for those who earned it. I and others here gave up guaranteed perks, cash back and travel miles with other cc's and by purchasing at IdeaCorp., versus competitors. Very disappointing how instead of rewarding your loyal customers, you turn your back on us. I equate this with promos that reward first time buyers or subscribers with additional discounts that don't apply to existing members.",
      author: "tz1XZ7s6uStC2hZVpPQhXgcdXPwxifByF3Ao",
      creation: "2020-12-04",
      nbvotes: 7 },
    { id: "5",
      winner: false,
      title: "Allowing @Gamer Coupons to be used online",
      desc: "I've noticed that there's been a large focus on used games & there's been several @gamer coupons for used games that have resulted in good deals. But the problem for many is that their local stores don't have a large selection of used games which makes the coupons \"useless\". Also, when there's deals like buy 2 get 1 free on all used games or buy any used game $30 or more get a free Unlocked membership these are also not enticing if there's little to no game to buy.",
      author: "tz1UUHt41ukVHcamQ5YZgGWsm6mXasVBt6Ln",
      creation: "2020-12-05",
      nbvotes: 2 },
    { id: "6",
      winner: false,
      title: "Additional Gamers Club Unlocked Benefits",
      desc: " -At least 1 exclusive video game related deal of the day per week - Exclusive preview of upcoming sales/promotions/deals per week or month. -Special coupon on your birthday.",
      author: "tz1cck7sNvM3TWkUA9VGWnyBW44uxMLz9vGg",
      creation: "2020-12-06",
      nbvotes: 7 },
    { id: "7",
      winner: false,
      title: "Huge gigantic banner",
      desc: "Put a huge, gigantic banner over the TV department stating free delivery for any TV over 50\". With a disclaimer that any TV's self delivered will not be returnable for physical damage\"",
      author: "tz1ZXf37ZNfVupt5GVyrPJ76q8kbjFuD2z7R",
      creation: "2020-12-07",
      nbvotes: 8 },
  ]
 */

export const githubUrl = "https://github.com/edukera/completium-dapp-ideabox"

export const appTitle = "Vote for the best ideas!"

export const network  = "edo2net"
export const endpoint = 'https://edonet-tezos.giganode.io/'
export const bcdUrl   = "https://better-call.dev/edo2net/" + contractAddress

export const appName = "IdeaCorp."

